import streamlit as st
import pandas as pd
import numpy as np
import joblib
from scipy.stats import poisson

st.set_page_config(page_title="Football Match Predictor", page_icon="⚽", layout="centered")

@st.cache_resource
def load_artifacts():
    return joblib.load('football_model_artifacts.joblib')

artifacts = load_artifacts()
model_home = artifacts['model_home']
model_away = artifacts['model_away']
team_stats = artifacts['team_stats']

def predict_match(home_team, away_team, is_neutral):
    h_stat = team_stats[home_team]
    a_stat = team_stats[away_team]

    features = pd.DataFrame([{
        'home_elo': h_stat['elo'],
        'away_elo': a_stat['elo'],
        'elo_diff': h_stat['elo'] - a_stat['elo'],
        'home_form_gs': h_stat['form_gs'],
        'home_form_gc': h_stat['form_gc'],
        'away_form_gs': a_stat['form_gs'],
        'away_form_gc': a_stat['form_gc'],
        'neutral': int(is_neutral)
    }])

    h_lambda = model_home.predict(features)[0]
    a_lambda = model_away.predict(features)[0]

    # Probability matrix
    max_goals = 8
    t1_probs = [poisson.pmf(i, h_lambda) for i in range(max_goals + 1)]
    t2_probs = [poisson.pmf(i, a_lambda) for i in range(max_goals + 1)]
    matrix = np.outer(t1_probs, t2_probs)

    max_idx = np.unravel_index(np.argmax(matrix), matrix.shape)
    score = f"{max_idx[0]} - {max_idx[1]}"

    h_win = round(np.sum(np.tril(matrix, -1)) * 100, 1)
    a_win = round(np.sum(np.triu(matrix, 1)) * 100, 1)
    draw = round(100.0 - (h_win + a_win), 1)

    return score, h_win, draw, a_win, h_lambda, a_lambda

# UI
st.title("⚽ International Football Match Predictor")
st.caption("Developed by **Nihat Valiyev**")
st.write("Using this program, you can predict the scores of upcoming national team matches based on official statistical analysis.")
st.warning("⚠️ **Disclaimer:** Predictions are generated by automated statistical models for educational purposes only. This is not financial or betting advice. :)")


EXCLUDED_TEAMS = {

    "Two Slices", "Two Sicilies", "German DR", "USSR", "Yugoslavia", "Czechoslovakia",
"Madrid", "Yerevan", "Barcelona", "London", "Munich",
"Catalonia", "Basque Country", "Corsica", "Silesia", "Brittany",
    "Armenia", "Artsakh", "Abkhazia", "South Ossetia", "Transnistria",
"Unknown", "Test"
}

teams = sorted([team for team in team_stats.keys() if team not in EXCLUDED_TEAMS])

col1, col2 = st.columns(2)
with col1:
    home_team = st.selectbox("Home team", teams, index=teams.index('Turkey') if 'Turkey' in teams else 0)
with col2:
    away_team = st.selectbox("Away team", teams, index=teams.index('Georgia') if 'Georgia' in teams else 1)

is_neutral = st.checkbox("Neutral Venue")

if st.button("Simulate the match"):
    if home_team == away_team:
        st.error("You can't choose the same team! Did you want to test me? ))) Of course, I had taken that into account.")
    else:
        score, h_win, draw, a_win, h_l, a_l = predict_match(home_team, away_team, is_neutral)

        st.markdown("---")
        
        
        col_score1, col_score2, col_score3 = st.columns([1, 2, 1])
        with col_score2:
            st.metric(
                label="⚽ Predicted Final Score", 
                value=f"{home_team}  {score}  {away_team}"
            )

        
        import plotly.express as px

        fig = px.pie(
            names=[f"{home_team} Win", "Draw", f"{away_team} Win"],
            values=[h_win, draw, a_win],
            color_discrete_sequence=['#2ecc71', '#f1c40f', '#e74c3c'],  #green,yellow,red
            hole=0.4
        )
        fig.update_layout(
            margin=dict(t=30, b=20, l=20, r=20),
            height=300,
            showlegend=True
        )
        st.plotly_chart(fig, use_container_width=True)

        
        c1, c2, c3 = st.columns(3)
        c1.metric(f"{home_team} Win", f"{h_win}%")
        c2.metric("Draw", f"{draw}%")
        c3.metric(f"{away_team} Win", f"{a_win}%")

        
        st.info(f"💡 Expected Goal Counts (xG): {home_team} = {h_l:.2f} | {away_team} = {a_l:.2f}")
